### ISSUE TITLE
Error in Huggett1993

### ISSUE THREAD

**Issue by kamecon** [vfitoolkit/vfitoolkit-matlab-replication#1] opened 2018-04-25 18:02 UTC
When I try to run the code I obtain the following error:

```{matlab}
Error using SSvalues_AggVars_Case1
Too many input arguments.

Error in Huggett1993_Fn (line 83)
SSvalues_AggVars=SSvalues_AggVars_Case1(StationaryDist, Policy, SSvaluesFn,Params, SSvalueParamNames,n_d, n_a, n_z, d_grid, a_grid,z_grid,pi_z,p_eqm, Parallel);

Error in Huggett1993 (line 56)
        Output=Huggett1993_Fn(n_a,n_e,n_q,Params, Parallel, vfoptions, simoptions) ;

```

In line 83 of  `Huggett1993_Fn`  the function call is:

```{matlab}
SSvalues_AggVars=SSvalues_AggVars_Case1(StationaryDist, Policy, SSvaluesFn,Params, SSvalueParamNames,n_d, n_a, n_z, d_grid, a_grid,z_grid,pi_z,p_eqm, Parallel);
```
But the definition of the function is 

```{matlab}
SSvalues_AggVars_Case1(StationaryDist, PolicyIndexes, SSvaluesFn, Parameters, SSvalueParamNames, n_d, n_a, n_z, d_grid, a_grid, z_grid, Parallel);
```
So in the function call the inputs `pi_z` and `p_eqm` generates the error.

In the line 85 of `Huggett1993_Fn` there is a typo
```{matlab}
eqm_MC=real(MarketClearance_Case1(SSvalues_AggVars,Params.q, GeneralEqmEqns, Params, GeneralEqmEqnParamNames));
```

I just comment that line and everything went fine 
 
Regards, Kamal

**Comment by robertdkirkby** [comment] 2018-05-01 23:50
Fixed. Thanks Kamal! Very much appreciate you letting me know.

Was due to one of the version updates of vfitoolkit, I hadn't rerun Huggett replication.

(p_eqm was no longer needed as an input as I decided it was much easier keeping all the prices in Params)

(MarketClearance_Case1 got renamed to GeneralEqmConditions_Case1. I realized this more general idea was better while doing some codes working with models  containing government budgets that I have almost finished.)

**Comment by kamecon** [comment] 2018-05-02 12:34
My pleasure Robert!

I am also getting errors in `Imrohoroglu1989` and `DiazGimenezPrescottAlvarezFitzgerald1992`. As soon as I figure out what happens, I will let you know.

In the case of `Imrohoroglu1989` I think is a problem with array dimensions, in the cases with aggregate shocks the distribution and policy matrices don't include the additional dimension

**Comment by robertdkirkby** [comment] 2018-05-16 05:47
Now fixed Imrohoroglu1989: 
https://github.com/vfitoolkit/vfitoolkit-matlab-replication/issues/2#issuecomment-389401469

**Comment by robertdkirkby** [comment] 2018-05-17 04:44
I ran DiazGimenezPrescottAlvarezFitzgerald1992 but did not get an error. Do you still get one, and if so what error message?

**Comment by kamecon** [comment] 2018-05-17 11:14
Robert, this is the error:

```{matlab}
Subscript indices must either be real positive integers or logicals.

Error in SSvalues_AggVars_Case1 (line 74)
        a_gridvals(i2,:)=num2cell(a_grid(sub));

Error in DiazGimenezPrescottAlvarezFitzgerald1992 (line 245)
    SSvalues_AggVars2=SSvalues_AggVars_Case1(StationaryDist, Policy, SSvaluesFn, Params, SSvalueParamNames, n_d, n_a, n_sz, d_grid, a_grid,sz_grid, 2);
```

**Comment by robertdkirkby** [comment] 2018-05-17 21:47
I am guessing it will be a numerical rounding error coming from using float 32 rather than float 64 bit numbers (many gpus do single rather than double-point floating arithmetic).

Take a look at output of
```
Policy=reshape(Policy,[numel(Policy),1]);
max(abs(Policy-round(Policy)))
```

If it gives a tiny number (say 10^(-12)) then it was likely that it is rounding error.

In this case you can just add
`vfoptions.policy_forceintegertype=1;`
near the beginning.

**Comment by robertdkirkby** [comment] 2018-05-17 21:48
i.e. what should be an integer, like 7, is instead coming out as 7+10^(-12) and this is then causing an error when trying to use it to index a matrix

**Comment by kamecon** [comment] 2018-05-21 10:09
Robert,

This is what I obtain

```{matlab}
Policy=reshape(Policy,[numel(Policy),1]);
max(abs(Policy-round(Policy)))

ans =

     0
```
Also I notice that in line 98 of `DiazGimenezPrescottAlvarezFitzgerald1992.m` the condition `foptions.policy_forceintegertype=1;` is already imposed


Inspecting the output of the function `SSvalues_AggVars_Case1` in line 74 (where the error happens) `a_gridvals(i2,:)=num2cell(a_grid(sub));` , `sub` is equal to

```{matlab}
sub =

     0   801
 ```

There is where the error `Subscript indices must either be real positive integers or logicals.` comes from.

**Comment by robertdkirkby** [comment] 2018-05-22 01:24
Hmm, not a rounding error then. 

I am guessing that it has something to do with trying to get from an index to a subscript that is outside the size of the matrix. (sub is created by ind2sub_homemade which turns a matrix index into a matrix subscript; for some reason the inbuilt matlab ind2sub does not do this in the way you might expect). (trying to access outside the size of the matrix is only reason I can think of for why it would possibly return a 0, is as much a guess as anything else)

Given that the code runs without error for me I am not sure what it might be caused by. According to git all the relevant m-files are synced between my computer and github. At some point I will try set up a clean install on some other machine but for now I'm not sure of the cause.

**Closed as completed** 2020-01-13 22:09 UTC
