### ISSUE TITLE
Error in GuerrieriLorenzoni2017

### ISSUE THREAD

**Issue by kamecon** [vfitoolkit/vfitoolkit-matlab-replication#4] opened 2022-03-12 19:30 UTC
Dear Robert,

When I run the replication file `GuerrieriLorenzoni2017.m` the following error appears:

```
Unable to perform assignment because dot indexing is not supported for variables of
this type.

Error in HeteroAgentStationaryEqm_Case1 (line 56)
        heteroagentoptions.multiGEcriterion=1;

Error in GuerrieriLorenzoni2017 (line 235)
    [p_eqm_initial,p_eqm_index_initial,
    MarketClearance_initial]=HeteroAgentStationaryEqm_Case1(V0, n_d, n_a, n_z, n_p,
    pi_z, d_grid, a_grid, z_grid, ReturnFn, FnsToEvaluate, GeneralEqmEqns, Params,
    DiscountFactorParamNames, ReturnFnParamNames, FnsToEvaluateParamNames,
    GeneralEqmEqnParamNames, GEPriceParamNames, heteroagentoptions, simoptions,
    vfoptions);
```
I have checked the function `HeteroAgentStationaryEqm_Case1` and the structure `heteroagentoptions` and did not found nothing apparently wrong.

Regards, Kamal.

**Comment by robertdkirkby** [comment] 2022-03-14 00:08
Thanks for letting me know. I am actually almost through cleaning up the GuerrieriLorenzoni2017 example code (to use what will be version 2 of VFI Toolkit, makes things much easier in terms of parameters, FnsToEvaluate and general eqm conditions). I will take a look at cleaning up the replication once I am done.

**Comment by kamecon** [comment] 2022-03-15 08:41
Hi Robert! Thanks for your response!

Please let me know when the code is clean. I'm vey interested in this example because I wish to implement something similar. If you have any idea about how to solve this problem, meanwhile, I will very much appreciate your help.

Regards, Kamal.

**Comment by robertdkirkby** [comment] 2022-03-16 08:34
I can see what the problem is, namely that the code has `heteroagentoptions` as something other than a structure (that error is what happens when Matlab tries to access, e.g., an array as if it was a structure). But why it occurs is not so obvious. I would double-check the order of the inputs in the command calling `HeteroAgentStationaryEqm_Case1` against the actual inputs (right-click and open it, look at the ordering there).

I will let you know once I finish cleaning and uploading the example.

**Comment by kamecon** [comment] 2022-03-16 09:52
Thank you very much, Robert! 

I will also take a deeper look at the function.

Cheers, Kamal.

**Comment by robertdkirkby** [comment] 2022-03-27 21:10
Hey Kamal,

have just pushed the updated version of GuerrieriLorenzoni2017_Example.m

It uses what will be version 2 of VFI Toolkit (should be released later this week, I am almost done). The differences are around making it much easier to use. You no longer need ReturnFnParamNames (it is just figured out internally), and the way you set up FnsToEvaluate is similarly simplified. It also changes the way you do general equilibrium equations so that you can just refer to both the parameters and any aggregates calculated from FnsToEvaluate by name. Makes reading models vastly easier and also allows the codes to provide much more useful feedback on how your, e.g., general equilibrium convergence is going.

Version 2 does break transition paths, but all other codes should continue to be backward compatible (e.g. value function iteration, aggregate variables, general equilibrium). I decided to break transition paths as they were not yet a major feature and because version 2 just makes them vastly simpler through the use of a new transpathoptions.GEnewprice=3 which allows you to define how the shooting algorithm updates. The example codes give an explanation of this where they set up the transition; so far there are GuerrieriLorenzoni2017 and also a transition based on Aiyagari1994, within the week I expect to also have an OLG transition based on ConesaKreuger1999.

Sorry that took so long, I have a fair bit of teaching at the moment so can only spare a day or two each week for this.

The example is at: [github.com/vfitoolkit/VFItoolkit-matlab-examples/tree/master/HeterogeneousAgentModels](https://github.com/vfitoolkit/VFItoolkit-matlab-examples/tree/master/HeterogeneousAgentModels)

I have no present plans to update the replications to v2 as it would be heaps of work for no obvious return. It should remain possible to run them by using github to download a copy of VFI Toolkit as it was on the date when the replication was released.

Note that transition paths are quite demanding on your gpu. Right now they need a fairly high end gpu, but given two or three years anyone will be able to run them.

If you run into any issues running the GuerrieriLorenzoni2017_Example please let me know.

**Comment by robertdkirkby** [comment] 2022-03-27 21:26
PS. I am closing this as an issue. I am not sure if github will let you comment on closed issues. But feel free to either open a new one or use forum: discourse.vfitoolkit.com

**Closed as completed by robertdkirkby** 2022-03-27 21:26 UTC
